In [97]:
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report



In [98]:
train_df = pd.read_csv("donnees_nettoyees_train.csv")
test_df = pd.read_csv("donnees_nettoyees_test.csv")

# Analyse exploratoire des données

### l'analyse a deja été faite avec mon app streamlit dedier a l'analyse exploratoire :
- gestion des valeurs nulles 
- gestion des outliers
- gestion des valeurs dupliquée

In [99]:
train_df.sample(10)

PassengerId  Survived  Pclass  \
169          221         1       3   
552          708         1       1   
347          449         1       3   
693          882         0       3   
574          734         0       2   
455          584         0       1   
125          161         0       3   
594          760         1       1   
9             13         0       3   
19            27         0       3   

                                                  Name     Sex   Age  SibSp  \
169                     Sunderland, Mr. Victor Francis    male  16.0      0   
552                  Calderhead, Mr. Edward Pennington    male  42.0      0   
347                     Baclini, Miss. Marie Catherine  female   5.0      2   
693                                 Markun, Mr. Johann    male  33.0      0   
574                         Berriman, Mr. William John    male  23.0      0   
455                                Ross, Mr. John Hugo    male  36.0      0   
125                           Cribb, Mr. John Hatfield    male  44.0      0   
594  Rothes, the Countess. of (Lucy Noel Martha Dye...  female  33.0      0   
9                       Saundercock, Mr. William Henry    male  20.0      0   
19                             Emir, Mr. Farred Chehab    male  28.0      0   

     Parch           Ticket     Fare    Cabin Embarked  
169      0  SOTON/OQ 392089   8.0500  B96 B98        S  
552      0         PC 17476  26.2875      E24        S  
347      1             2666  19.2583  B96 B98        C  
693      0           349257   7.8958  B96 B98        S  
574      0            28425  13.0000  B96 B98        S  
455      0            13049  40.1250      A10        C  
125      1           371362  16.1000  B96 B98        S  
594      0           110152  86.5000      B77        S  
9        0        A/5. 2151   8.0500  B96 B98        S  
19       0             2631   7.2250  B96 B98        C

In [100]:
test_df.sample(10)

PassengerId  Pclass                                   Name     Sex   Age  \
375         1267       1               Bowen, Miss. Grace Scott  female  45.0   
53           945       1             Fortune, Miss. Ethel Flora  female  28.0   
289         1181       3                       Ford, Mr. Arthur    male  27.0   
171         1063       3                    Zakarian, Mr. Ortin    male  27.0   
140         1032       3            Goodwin, Miss. Jessie Allis  female  10.0   
86           978       3                     Barry, Miss. Julia  female  27.0   
317         1209       2             Rogers, Mr. Reginald Harry    male  19.0   
150         1042       1  Earnshaw, Mrs. Boulton (Olive Potter)  female  23.0   
403         1295       1                 Carrau, Mr. Jose Pedro    male  17.0   
136         1028       3              Zakarian, Mr. Mapriededer    male  26.5   

     SibSp  Parch    Ticket      Fare            Cabin Embarked  
375      0      0  PC 17608  262.3750  B57 B59 B63 B66        C  
53       3      2     19950  263.0000      C23 C25 C27        S  
289      0      0  A/5 1478    8.0500  B57 B59 B63 B66        S  
171      0      0      2670    7.2250  B57 B59 B63 B66        C  
140      5      2   CA 2144   46.9000  B57 B59 B63 B66        S  
86       0      0    330844    7.8792  B57 B59 B63 B66        Q  
317      0      0     28004   10.5000  B57 B59 B63 B66        S  
150      0      1     11767   83.1583              C54        C  
403      0      0    113059   47.1000  B57 B59 B63 B66        S  
136      0      0      2656    7.2250  B57 B59 B63 B66        C

In [101]:
print(train_df.describe())
print("\n")
print(test_df.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   701.000000  701.000000  701.000000  701.000000  701.000000   
mean    450.559201    0.358060    2.370899   29.360913    0.285307   
std     257.423833    0.479772    0.804955    9.474265    0.508413   
min       1.000000    0.000000    1.000000    4.000000    0.000000   
25%     227.000000    0.000000    2.000000   24.000000    0.000000   
50%     453.000000    0.000000    3.000000   28.000000    0.000000   
75%     671.000000    1.000000    3.000000   34.000000    1.000000   
max     891.000000    1.000000    3.000000   55.000000    2.000000   

            Parch        Fare  
count  701.000000  701.000000  
mean     0.105563   21.573501  
std      0.307498   22.914738  
min      0.000000    0.000000  
25%      0.000000    7.879200  
50%      0.000000   11.241700  
75%      0.000000   26.000000  
max      1.000000  113.275000  


       PassengerId      Pclass         Age       SibSp       Parch        Fare


In [102]:
print(train_df.columns, "\n\n", test_df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object') 

 Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [103]:
train_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [104]:
train_df.duplicated().sum()

0

In [105]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  701 non-null    int64  
 1   Survived     701 non-null    int64  
 2   Pclass       701 non-null    int64  
 3   Name         701 non-null    object 
 4   Sex          701 non-null    object 
 5   Age          701 non-null    float64
 6   SibSp        701 non-null    int64  
 7   Parch        701 non-null    int64  
 8   Ticket       701 non-null    object 
 9   Fare         701 non-null    float64
 10  Cabin        701 non-null    object 
 11  Embarked     701 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 65.8+ KB


In [106]:
train_df.drop(['Name', 'Ticket'], axis=1, inplace=True)
test_df.drop(['Name', 'Ticket'], axis=1, inplace=True)


In [107]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  701 non-null    int64  
 1   Survived     701 non-null    int64  
 2   Pclass       701 non-null    int64  
 3   Sex          701 non-null    object 
 4   Age          701 non-null    float64
 5   SibSp        701 non-null    int64  
 6   Parch        701 non-null    int64  
 7   Fare         701 non-null    float64
 8   Cabin        701 non-null    object 
 9   Embarked     701 non-null    object 
dtypes: float64(2), int64(5), object(3)
memory usage: 54.9+ KB


### Encodons les caracteristiques categorielles

In [108]:
categorical = train_df.select_dtypes(include = "object").columns
le = LabelEncoder()

for col in categorical :
    train_df[col] = le.fit_transform(train_df[col])

categorical1 = test_df.select_dtypes(include = "object").columns
le_ = LabelEncoder()
for col in categorical1 :
    test_df[col] = le.fit_transform(test_df[col])

In [109]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  701 non-null    int64  
 1   Survived     701 non-null    int64  
 2   Pclass       701 non-null    int64  
 3   Sex          701 non-null    int32  
 4   Age          701 non-null    float64
 5   SibSp        701 non-null    int64  
 6   Parch        701 non-null    int64  
 7   Fare         701 non-null    float64
 8   Cabin        701 non-null    int32  
 9   Embarked     701 non-null    int32  
dtypes: float64(2), int32(3), int64(5)
memory usage: 46.7 KB


In [110]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Sex          418 non-null    int32  
 3   Age          418 non-null    float64
 4   SibSp        418 non-null    int64  
 5   Parch        418 non-null    int64  
 6   Fare         418 non-null    float64
 7   Cabin        418 non-null    int32  
 8   Embarked     418 non-null    int32  
dtypes: float64(2), int32(3), int64(4)
memory usage: 24.6 KB


In [111]:
train_df.head(10)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  \
0            1         0       3    1  22.0      1      0   7.2500     29   
1            2         1       1    0  38.0      1      0  71.2833     52   
2            3         1       3    0  26.0      0      0   7.9250     29   
3            4         1       1    0  35.0      1      0  53.1000     36   
4            5         0       3    1  35.0      0      0   8.0500     29   
5            6         0       3    1  28.0      0      0   8.4583     29   
6            7         0       1    1  54.0      0      0  51.8625     88   
7           10         1       2    0  14.0      1      0  30.0708     29   
8           11         1       3    0   4.0      1      1  16.7000    101   
9           13         0       3    1  20.0      0      0   8.0500     29   

   Embarked  
0         2  
1         0  
2         2  
3         2  
4         2  
5         1  
6         2  
7         0  
8         2  
9         2

### **appliquons notre modele**

In [112]:
X = train_df.drop(['Survived', 'PassengerId','SibSp','Parch'], axis=1)
y = train_df['Survived']

In [113]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, random_state=42)

In [114]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [115]:
y_pred = model.predict(X_val)


In [116]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [117]:
np.array(y_val)

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [118]:
accuracy_score(y_val, y_pred)

0.8226950354609929

In [119]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.87      0.86        90
           1       0.76      0.75      0.75        51

    accuracy                           0.82       141
   macro avg       0.81      0.81      0.81       141
weighted avg       0.82      0.82      0.82       141



In [120]:
test_df.drop(['SibSp', 'Parch'],axis = 1,  inplace = True)

test_df

PassengerId  Pclass  Sex   Age      Fare  Cabin  Embarked
0            892       3    1  34.5    7.8292     15         1
1            893       3    0  47.0    7.0000     15         2
2            894       2    1  62.0    9.6875     15         1
3            895       3    1  27.0    8.6625     15         2
4            896       3    0  22.0   12.2875     15         2
..           ...     ...  ...   ...       ...    ...       ...
413         1305       3    1  27.0    8.0500     15         2
414         1306       1    0  39.0  108.9000     22         0
415         1307       3    1  38.5    7.2500     15         2
416         1308       3    1  27.0    8.0500     15         2
417         1309       3    1  27.0   22.3583     15         0

[418 rows x 7 columns]

In [121]:
X_train

Pclass  Sex   Age     Fare  Cabin  Embarked
165       3    0  27.0   7.9250     29         2
542       3    1  44.0   8.0500     29         2
284       3    0  28.0   7.7500     29         1
360       2    1  48.0  13.0000     29         2
110       1    1  24.0  79.2000     27         0
..      ...  ...   ...      ...    ...       ...
71        3    1  28.0   8.0500     29         2
106       2    1  25.0  13.0000     29         2
270       3    1  15.0   7.2292     29         0
435       3    1  40.0   7.8958     29         2
102       3    1  33.0   7.8958     29         0

[560 rows x 6 columns]

In [122]:
X_test = test_df.drop('PassengerId', axis=1)
y_test_pred = model.predict(X_test)

In [123]:
y_test_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [124]:
submit = pd.DataFrame(
    {
    "PassengerId":test_df['PassengerId'] ,
    "Survived" : y_test_pred
}
)

In [125]:
submit.to_csv("submit_titanic1.csv", index = False)